nav:
- index.md
- access-control.md
- anti-patterns.md
- best-practices.md
- block-display.md
- caching-configuration.md
- code-reference-map.md
- config-export-recipes.md
- custom-argument-handler.md
- custom-cache-plugin.md
- custom-display-plugin.md
- custom-field-handler.md
- custom-filter-handler.md
- custom-relationship-handler.md
- custom-sort-handler.md
- custom-style-row-plugins.md
- display-configuration.md
- feed-attachment-displays.md
- fields-configuration.md
- filters-exposed.md
- page-display.md
- pager-configuration.md
- programmatic-modification.md
- query-settings.md
- relationships.md
- rest-export-display.md
- security-performance.md
- sort-contextual.md
- sources-maintenance.md
- style-row-plugins.md
- view-config-schema.md
- views-data-integration.md
- views-overview.md
- views-plugin-architecture.md
append_unmatched: true
