nav:
- index.md
- architecture.md
- best-practices-performance.md
- code-reference-map.md
- column-types-data.md
- column-types-datetime.md
- column-types-file.md
- column-types-numeric.md
- column-types-reference.md
- column-types-text.md
- config-first-creation.md
- custom-plugins.md
- datetime-fields.md
- development-standards.md
- entity-references.md
- feeds-integration.md
- field-level-formatters.md
- field-level-widgets.md
- files-images.md
- link-fields.md
- overview.md
- schema-updates.md
- sdc-view-modes.md
- sub-modules.md
- token-support.md
- views-integration.md
- widget-plugins-overview.md
append_unmatched: true
